### ISSUE TITLE
could not get this to build

### ISSUE THREAD

**Issue by blp** [another-s347/rusty-p4#2]
This looks like a useful project, I would very much like to play with it!

With nightly rust (which is required) and the master branch, I get a lot of errors of this form while building:

```
error[E0277]: the trait bound `proto::v1::WriteRequest: prost::message::Message` is not satisfied
   --> /home/bpfaff/dddp/rusty-p4/target/debug/build/rusty-p4-proto-13932b727387435a/out/p4.v1.rs:953:199
    |
953 | ...rshaller { ser: ::grpcio::pr_ser, de: ::grpcio::pr_de }, resp_mar: ::grpcio::Marshaller { ser: ::grpcio::pr_ser, de: ::grpcio::pr_de }...
    |                    ^^^^^^^^^^^^^^^^ the trait `prost::message::Message` is not implemented for `proto::v1::WriteRequest`
    | 
   ::: /home/bpfaff/.cargo/registry/src/github.com-1ecc6299db9ec823/grpcio-0.5.4/src/codec.rs:57:19
    |
57  |     pub fn ser<M: Message, B: BufMut>(msg: &M, buf: &mut B) {
    |                   ------- required by this bound in `grpcio::ser`
```

I played with it for some time and could not figure it out. I am a relative novice in Rust.

On the dev branch, with nightly rust, `rusty-p4` builds OK, but so far I haven't been able to massage the first example from the Readme into working (although I'm still working on it). There isn't, for example, anything in the tree called P4InfoHelper, which the example tries to use. I could also not find where ParamValue::of is supposed to come from. And the `example/` crate fails to build with errors that start out like this:

```
error: expected `:`
  --> src/bin/example.rs:30:17
   |
30 |             pipe="IngressPipeImpl";
   |                 ^
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: expected `:`
```

**Comment by another-s347** [comment]
Sorry, the development of this project has been delayed for serveral months due to my personal reason. I will look into the issue and update the project ASAP next month.

The readme is heavily out-dated cause the design had changed a lot. Please try benchmark which should work.

**Comment by blp** [comment]
Thanks, I'll look forward to updates.

**Comment by another-s347** [comment]
The design have been updated now, as well as examples. But there is still a lot of work to do, so any feedback, issue or pr are welcome :)
